container:
  image: jekyll/jekyll:latest

build_task:
  prebuild_script: chmod -R +rwt /tmp
  build_script: jekyll build -d $JEKYLL_DATA_DIR
  npm_install_script: npm install
  lint_script: npm run lint:css
