container:
  image: jekyll/jekyll:latest

build_task:
  # We're using the vanilla jekyll/jekyll container, which makes everything
  # unavailable except $JEKYLL_DATA_DIR.
  chmod_script: chmod +t /tmp
  build_script: jekyll build -d $JEKYLL_DATA_DIR
  npm_install_script: npm install
  css_lint_script: npm run lint:css
  # TODO: add full build including `npm run build:css` (must solve chown issues)
  # TODO: add linkchecking (depends on having a Dockerfile with added Dart)

# TODO: add deployment script (https://cirrus-ci.org/guide/docker-builder/)
