name: Egamebook
url: https://egamebook.com
timezone: Europe/Prague

markdown: redcarpet

redcarpet:
  extensions:
    - smart
    - footnotes

highlighter: pygments

permalink: /blog/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      author: "Filip Hracek"

include:
  - .well-known

exclude:
  - "*.json"
  - "*.sh"
  - .*rc
  - .sass-cache
  - Gemfile*
  - makefile
  - node_modules
  - postcss.config.js
  - vendor/bundle
  - .idea

keep_files:
  - css/main.min.css
  - css/main.min.css.map
