name: Egamebook
url: http://egamebook.com
timezone: Europe/Prague

plugins:
  - jekyll-assets

assets:
  sources:
    - _sass/main

markdown: redcarpet

redcarpet:
  extensions:
    - smart
    - footnotes

highlighter: pygments

permalink: /blog/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      author: "Filip Hracek"

include: [".well-known"]

exclude:
  - fonts
  - Gemfile*
